### PR TITLE
the user can set to be prompted before launching all the tasks

### PR DESCRIPTION
**Pull request by NoriSte**
issue #6 
The user will be prompted just before the extension launches all the tasks
screen shot 2018-07-26 at 18 42 47
I'm not 100% satisfied because I'd rather have an API for a prompt similar to the "Update VSCode" one but, if I haven't missed it, it isn't possible.
I'll look forward to your feedbacks
Thank you

### CODE REVIEW

**Comment by philfontaine** [comment]
General question: what feels more right to you?
1. A global configuration to prompt or not for every task
2. A per task configuration to prompt or not (i.e. auto: 'prompt')

**Comment by philfontaine** [comment]
I think option 2 would be preferable (in my opinion) because the choice to autostart a task is configurable _per task_, so it would feel more natural if the prompt worked that way too.

I already had started a branch before you announced you would make a PR.
I spent some time trying to fix #5 too, and I just came up with a branch (feature/fix#5and#6) that would fix both issues.

Thank you for your PR, but unfortunately I don't think it will be needed, unless it is decided that option 1 is a better choice.

**Comment by NoriSte** [comment]
Both are some interesting approaches, to me the option 1 is more useful, imagine this (mine) scenario:
- I have configured 2-4 auto tasks for every project
- I open up another project just to take a look at some implementations
- I'd like to stop the auto-execution of the tasks
in this case, it'll be annoying to have to be prompted for every task (because I don't want to work on the project at the moment). 

But option 2 makes absolutely sense because sometimes I set as "auto" some tasks that are relative to what I'm doing today, tomorrow I'll probably change the list of tasks to be launched (some will stay and some will change).

So to me both are fine and it could be left to the user to choose how to configure the tasks.

A generic and less confusing solution could be:
- no generic setup, just a per-task setup
- the prompt for every task could have three option:
• launch the "task 1"
• don't launch the "task 1"
• stop launching all the tasks
the third option is available at every prompt

What do you think?

**Comment by philfontaine** [comment]
I think what you last proposed would have been to complicated and confusing to implement. I went back to your original idea to introduce a global setting, which after reflection seems like a more important use case to cover.

If I had to do it again I would have started from your PR, but it was too late for that when I changed my mind. Sorry about that, and thank you for your idea and contribution. Your PR was a good inspiration.

I'm closing this, the feature is currently being developed in branch feature/fix#5and#6.

**Pull request closed without merging**
